name: Build
on: push

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docke image
        run: docker-compose -f backend/docker-compose.yml build

